version: '3'

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    network_mode: host
    
  beaverbot:
    user: root
    depends_on: 
      - ros-master
    image: beaverbot:noetic
    build:
      context: ..
      dockerfile: ./beaverbot_dockerfiles/Dockerfile
    container_name: beaverbot
    volumes:
      - "../:/root/catkin_ws/src/"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/tmp/.docker.xauth:/tmp/.docker.xauth"
      - "/dev:/dev"
    environment:
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
      - "QT_X11_NO_MITSHM=1"
    privileged: True
    network_mode: host
    tty: True
    stdin_open: True
    entrypoint:
      - bash 
      - -c
    command: > 
      "source /opt/ros/noetic/setup.bash &&
      source /root/catkin_ws/devel/setup.bash &&
      sleep 2 &&
      roslaunch beaverbot_launch bringup.launch"


  robot_communication:
    user: root
    depends_on: 
      - ros-master
    image: beaverbot:melodic
    build:
      context: ..
      dockerfile: ./beaverbot_dockerfiles/Dockerfile.melodic
    container_name: beaverbot_communication
    privileged: True
    network_mode: host
    tty: True
    stdin_open: True
    volumes:
      - "/dev:/dev"
    entrypoint:
      - bash 
      - -c
    command: > 
      "source /opt/ros/melodic/setup.bash &&
      source /root/catkin_ws/devel/setup.bash &&
      sleep 2 &&
      roslaunch beaverbot_driver beaverbot_driver.launch"

